### ISSUE TITLE
PackageIntegrityCheckFailed when installing

### ISSUE THREAD

**Issue by alexeyr** [tecosaur/LaTeX-Utilities#379]
When I try to install v0.4.9, I get this error:
```
2023-02-16 21:29:13.980 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/Alexey/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/Alexey/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-16 21:29:14.006 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/Alexey/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/Alexey/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
```
Installing from VSIX manually works.

**Comment by PhysicsBeyond** [comment]
Same problem as above. Manual installations seems to work. Thanks.

**Comment by leoleoasd** [comment]
I didn't make any changes to the vsix in the marketplace. Maybe a vscode issue.

**Comment by leoleoasd** [comment]
@alexeyr @PhysicsBeyond Can you provide your environment (for example, OS, vscode version, etc.) so I can report this to vscode team?

**Comment by leoleoasd** [comment]
Hmmm it seems that installing other extensions works fine. I'll re-publish it when I got home

**Comment by alexeyr** [comment]
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by aathan** [comment]
I'm currently getting the same error.

**Comment by leoleoasd** [comment]
Can you try again now?

**Comment by leoleoasd** [comment]
This is resolved now.
