### ISSUE TITLE
Non delimited bibtex fields make the parser crash

### ISSUE THREAD

**Issue by jlelong** [tecosaur/LaTeX-Utilities#97]
This is reported in James-Yu/LaTeX-Workshop/issues/1803.

Consider

```bibtex
@reference{dictionary_of_contemporary_english,
    editor = "",
    edition = {Fourth edition},
    title = "Dictionary of Contemporary English",
    publisher = "Longman",
    year = 2003,
    ISBN = 1-405-80673-7
}
```

and you get

```
▶ [Extension Host]
rejected promise not handled within 1 second: SyntaxError: Expected "#", ",", "\r\n", "}", or [ \t\n] but "@" found.
  t.log @ console.ts:137
▶ [Extension Host] 
stack trace: SyntaxError: Expected "#", ",", "\r\n", "}", or [ \t\n] but "@" found.
    at peg$buildStructuredError (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:366:12)
    at Object.peg$parse [as parse] (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser_simple.js:2011:11)
    at Object.parse (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/latex-utensils/out/src/bibtex/bibtex_parser.js:21:30)
    at Function.parseBibtex (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/out/src/components/parser/syntax_worker.js:12:42)
    at process.<anonymous> (/home/nawordar/.vscode/extensions/james-yu.latex-workshop-8.4.2/node_modules/workerpool/dist/workerpool.min.js:25:16221)
    at process.emit (events.js:200:13)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
  t.log @ console.ts:137
```

**Comment by tecosaur** [comment]
Thanks for the report, however I fail to immediately see how this extension causes that, since all the logs seem to be to do with LW.

I'm sure I'll soon feel silly got along this, but would you be able to step the issue out a bit more for me?

**Comment by jlelong** [comment]
My bad, I wanted to post in [https://github.com/tamuratak/latex-utensils](https://github.com/tamuratak/latex-utensils).

**Comment by tecosaur** [comment]
All these similarly named things are a tad confusing aren't they :P
